### ISSUE TITLE
False reported "No .licrc file found in the root of your repo" even following documentation.

### ISSUE THREAD

**Issue by rk0cc** [licensebat/licensebat#17]
I have no idea why I pushed [configuration file to root directory already](https://github.com/rk0cc/anitemp/blob/main/.licrc) and still reported no file found with these pull request:

* [Anitemp PR 4](https://github.com/rk0cc/anitemp/pull/4)
* [Anitemp PR 5](https://github.com/rk0cc/anitemp/pull/5)

I tried to delete and push the file to head branch directly and still reported not found.

**Comment by robertohuertasm** [comment]
Are you using the GitHub app or the action?

**Comment by rk0cc** [comment]
> Are you using the GitHub app or the action?

GitHub App

**Comment by robertohuertasm** [comment]
Hi @rk0cc sorry for the late response. The thing is that the `.licrc` file is not well formed and it's mandatory to include the `[dependencies]` section.

I'll change the error message so it can be more meaningful.

**Comment by rk0cc** [comment]
> Hi @rk0cc sorry for the late response. The thing is that the `.licrc` file is not well formed and it's mandatory to include the `[dependencies]` section.
> 
> I'll change the error message so it can be more meaningful.

@robertohuertasm In fact, I followed [your gist](https://gist.github.com/robertohuertasm/4770217e40209ad6a65acb1d725c3f87) to setup the file which also not mentioned which sections and keys are mandatory or not. Please update as soon as possible to prevent new user misunderstood.

**Comment by robertohuertasm** [comment]
Hi @rk0cc you're right. I thought it was obvious that all of them were mandatory but I can see it's not. I'll add a note there. Thanks for raising this issue!
