### ISSUE TITLE
README not correct

### ISSUE THREAD

**Issue by wiz21b** [licensebat/licensebat#24]
I don't want to sound like a zealot, but this sentence:

> Let's say, for instance, that you are building a commercial application. In that case, you may consider avoiding the use of some software with a restrictive license like GPL.

is not correct. One wants to avoid GPL because one wants to write proprietary software, not commercial software. GPL software can perfectly be commercial. I understand that "commercial" may be easier to understand for many but, to GPL advocates, the issue is not the commercial nature of software but the fact it is proprietary... So replacing "commercial" by "proprietary" in the sentence would be correct.

**Comment by robertohuertasm** [comment]
Fair point! Fixed as per your suggestion! Thanks for taking the time to create this issue!
