### ISSUE TITLE
`licensebat-js` does not support lockfile-version 3

### ISSUE THREAD

**Issue by ericcornelissen** [licensebat/licensebat#31]
Trying out Licensebat on [a repository of mine](https://github.com/ericcornelissen/svgo-action) I ran into a problem (got the output `No collector found for dependency file`). From my investigation this is due to the fact that my project uses [lockfile version](https://docs.npmjs.com/cli/v9/using-npm/config#lockfile-version) 3. In contrast to versions 1 and 2, version 3 does not have [`"dependencies"`](https://github.com/licensebat/licensebat/blob/30303547b0e809fe3af03e7bde63a6f64091a70d/licensebat-js/src/collector/npm_dependency.rs#L15) field. Instead, it has `"packages"` (also present in version 2, not in version 1).

**Comment by robertohuertasm** [comment]
@ericcornelissen you're right. I created #27 the other day in anticipation of this but I was not aware that version 3 was already being used. I'll try to work on this to avoid issues like yours. Thank you for reporting this!

**Comment by robertohuertasm** [comment]
Created [this new crate](https://crates.io/crates/package-lock-json-parser)to support v3. I'll keep you posted once everything is deployed.

It will probably take 30 mins.

If you test it again in your repo, I'll be happy to receive your feedback. 🙌🏻

**Comment by robertohuertasm** [comment]
@ericcornelissen it should be working now.

**Comment by ericcornelissen** [comment]
Works perfectly on my end, thanks @robertohuertasm!

**Comment by robertohuertasm** [comment]
Thanks you @ericcornelissen for the feedback!
