### ISSUE TITLE
Python Poetry support

### ISSUE THREAD

**Issue by RiccardoLincetto** [licensebat/licensebat#42]
Hi, I was trying this app in a python poetry project and found out that it is not compatible with `poetry.lock`. Is it a matter of lock format or of dependency manager support?

**Comment by robertohuertasm** [comment]
Hi @RiccardoLincetto. it's just a matter of not having time to cover all the languages :blush: My knowledge of Python is not really relevant so I'm more focused on the languages I'm more familiar with. Of course, I'll be happy to review a PR adding support for Python.

**Comment by RiccardoLincetto** [comment]
Oh I thought Python was supported because I saw the logo in the licensebat.com page. Unfortunately I'm not really familiar with license checking myself, I wouldn't be able to create a PR for this repo, that's why I was looking for something ready made 😬

**Comment by robertohuertasm** [comment]
Oh, I see. There are some logos that were greyed out, but I can see that it may be confusing. I'll consider removing them to avoid this kind of confusion in the future. Thanks in any case for your feedback!

**Comment by RiccardoLincetto** [comment]
Oh, that probably explains why: I was visiting the page with the Dark Reader plugin, so the color pattern was different in my browser, and I guess I didn't see that it was greyed out :)
